analyzer:
  errors:
    avoid_redundant_argument_values: ignore
    deprecated_member_use: ignore
    unused_local_variable: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_child_properties_last: true
    use_super_parameters: true
    use_key_in_widget_constructors: false
    avoid_unnecessary_containers: true
    avoid_redundant_argument_values: true
    avoid_relative_lib_imports: false
    prefer_const_literals_to_create_immutables: true
    unnecessary_null_checks: true
    prefer_null_aware_operators: true
    depend_on_referenced_packages: false