name: axis
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Routing
  go_router: ^14.8.1

  # Firebase
  firebase_core: 4.11.0
  firebase_auth: 6.5.3
  cloud_firestore: 6.6.0

  # UI
  google_fonts: ^6.2.1
  intl: ^0.20.2

  # Forms
  flutter_form_builder: ^10.1.0

  # Serialization
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # Hooks
  flutter_hooks: ^0.21.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.5.4
  riverpod_generator: ^2.6.5
  freezed: ^3.0.6
  json_serializable: ^6.9.5

  # Testing
  mocktail: ^1.0.4

flutter:
  uses-material-design: true